name: Node.js CI

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust the Node.js version as needed

      # Step 3: Debug - List files in the root directory
      - name: List files in the root directory
        run: ls -la

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build the project (if applicable)
      - name: Build the project
        run: npm run build --if-present


      # Step 7: Debug - Check installed dependencies
      - name: List installed dependencies
        run: npm list
